name: doctor_console
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  awesome_extensions: ^2.0.9
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  fluttertoast: ^8.2.2
  form_builder_validators: ^9.1.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
