name: doctor_console
description: Doctor In Physics Payment Console
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  appwrite: ^13.0.0
  awesome_extensions: ^2.0.17
  crypto: ^3.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  excel: ^4.0.6
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  fluttertoast: ^8.2.8
  form_builder_validators: ^11.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image: ^4.2.0
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  pdf: ^3.11.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
